### ISSUE TITLE
Make a "Company Page" Component

### ISSUE THREAD

**Issue by nbry** [derekm28/H.E.A.A.T.#1]
### Objective:
`NikePage`, `GucciPage`, `JordanPage`, etc all have similar logic. Try to create and implement one component that renders dynamically, based on brand.

### Context:
It seems like the you could pass a prop `brand` and change `params` based on brand.

**Comment by derekm28** [comment]
resolved in [PR #3 ](https://github.com/derekm28/H.E.A.A.T./pull/3)
